### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Foxiseminger** [covernts/CustomWraithCodes#1]
question

**Comment by Foxiseminger** [comment]
@covernts

**Comment by covernts** [comment]
Read the README.

**Comment by covernts** [comment]
Also, please do not ping me on GitHub. If you have questions, message me on discord. (@covernts)

**Comment by FoxyWorld1** [comment]
> Read the README.

I did

**Comment by covernts** [comment]
Then there should be no issue. Message me on discord for further follow ups.
